name: CI

on: [push, pull_request]


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.7, 3.8, 3.9]
    environment: ci
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install pyscf
        run: ./.github/workflows/install_pyscf.sh
     #- name: build lib
        #run: ./.github/workflows/build_lib.sh
      - name: test
        run: ./.github/workflows/run_test.sh
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./pyscfad/coverage.xml
